apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: p1y0hd7k3-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:6dce1df11b8155fea201ef6392d41a90d9816e6a@sha256:68d357ccb479a6a7cbb3998822ac13d6bcc5bc667f3ecdba44ef9e8af59d4509
        name: container-image  
